name: Buid & Push
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: "bootJar :test --info --build-cache"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ph-ee-connector-ams-paygops:${{ github.sha }}
